name: 📤 Test envío último newsletter

on:
  workflow_dispatch:       # un clic y listo

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar deps mínimas
        run: pip install markdown jinja2 premailer

      - name: Encontrar el último newsletter y enviarlo
        env:
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
        run: |
          latest_md=$(ls -t salida/*-newsletter.md | head -n1)
          echo "📄 Enviando $latest_md"
          python enviar_newsletter.py --md "$latest_md"
